// <auto-generated />
namespace InventorySystem.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Third1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Third1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803252023446_Third1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
